url: "https://otherpeopleucsd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/honey_daisy" # the subpath of your site, e.g. /blog
title: "other people" # the name of your site, e.g. ACME Corp.
